//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkimda
    {
        public int id { get; set; }
        public string Egitim { get; set; }
        public string isDeneyimlerim { get; set; }
        public string iletisimAciklama { get; set; }
        public string AdSoyad { get; set; }
        public string Foto { get; set; }
        public string Unvan { get; set; }
    }
}
