//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYetenekler
    {
        public byte id { get; set; }
        public string Yetenek { get; set; }
        public Nullable<byte> Derece { get; set; }
    }
}
